### ISSUE TITLE
OSError: Cannot parse file b'.\\Model\\Block5_Model\\saved_model.pb': Wrong wire type in tag..

### ISSUE THREAD

**Issue by deleteblackmage** [jackwangshanghai/CS8321HW2_Decoder#1]
When:

python Sample.py

Traceback (most recent call last):
  File "C:\Users\angel\Anaconda3\lib\site-packages\tensorflow_core\python\saved_model\loader_impl.py", line 68, in parse_saved_model
    saved_model.ParseFromString(file_content)
  File "C:\Users\angel\Anaconda3\lib\site-packages\google\protobuf\message.py", line 187, in ParseFromString
    return self.MergeFromString(serialized)
  File "C:\Users\angel\Anaconda3\lib\site-packages\google\protobuf\internal\python_message.py", line 1127, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "C:\Users\angel\Anaconda3\lib\site-packages\google\protobuf\internal\python_message.py", line 1181, in InternalParse
    buffer, new_pos, wire_type)  # pylint: disable=protected-access
  File "C:\Users\angel\Anaconda3\lib\site-packages\google\protobuf\internal\decoder.py", line 973, in _DecodeUnknownField
    raise _DecodeError('Wrong wire type in tag.')
google.protobuf.message.DecodeError: Wrong wire type in tag.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/Study/CS8321/CS8321HW2_Decoder-master/CS8321HW2_Decoder-master/Sample.py", line 38, in <module>
    AE = VGG19AE('.\Model')
  File "D:/Study/CS8321/CS8321HW2_Decoder-master/CS8321HW2_Decoder-master/Sample.py", line 8, in __init__
    ModelBlock5 = tf.keras.models.load_model(files_path + '\Block5_Model', compile = False)
  File "C:\Users\angel\Anaconda3\lib\site-packages\tensorflow_core\python\keras\saving\save.py", line 149, in load_model
    loader_impl.parse_saved_model(filepath)
  File "C:\Users\angel\Anaconda3\lib\site-packages\tensorflow_core\python\saved_model\loader_impl.py", line 71, in parse_saved_model
    raise IOError("Cannot parse file %s: %s." % (path_to_pb, str(e)))
OSError: Cannot parse file b'.\\Model\\Block5_Model\\saved_model.pb': Wrong wire type in tag..

Try to rename the path but still don't work……

**Comment by jackwangshanghai** [comment]
Fix by using Pathlib, Please try again.

**Comment by deleteblackmage** [comment]
OSError: Cannot parse file b'Model\\Block5_Model\\saved_model.pb': Wrong wire type in tag..

Sorry, still the same error……

And I've sent an email to your school mailbox if I‘ve typed right, would you mind check and add my wechat? Cause I have a lot of problem about the assignment……

**Comment by jackwangshanghai** [comment]
Please make sure you running on TensorFlow 2.0 or 2,1 with python 3.7.x

You can generate a new anaconda envs with and force install TF2.1 by using conda-forge channel.

the following command can help install 2.1 if not found using 2.0

conda create -n tfn -c conda-forge tensorflow=2.1 python=3.7 
conda activate tfn
